default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRESQL_USERNAME'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: simpleblog_development

test:
  <<: *default
  database: simpleblog_test

production:
  <<: *default
  database: simpleblog_production
  username: simpleblog
  password: <%= ENV['SIMPLEBLOG_DATABASE_PASSWORD'] %>
